require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'simplegarden' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'simplegardenTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'Permission-LocationAlways', :path => "../node_modules/react-native-permissions/ios/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "../node_modules/react-native-permissions/ios/LocationWhenInUse.podspec"
end

target 'simplegarden-tvOS' do
  # Pods for simplegarden-tvOS

  target 'simplegarden-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
